export const GET_PHOTOS_FROM_NASA = "GET_PHOTOS_FROM_NASA";
export const GET_PHOTOS_BY_FILTER = "GET_PHOTOS_BY_FILTER";
export const GET_MANIFESTS_BY_ROVER_MODEL = "GET_MANIFESTS_BY_ROVER_MODEL";
// export const FILTER_PHOTOS_BY_CAMERA = "FILTER_PHOTOS_BY_CAMERA";
export const GET_PHOTOS_BY_EARTH_DATE = "GET_PHOTOS_BY_EARTH_DATE";
export const GET_PHOTOS_BY_SEARCH = "GET_PHOTOS_BY_SEARCH";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const DELETE_FROM_FAVORITES = "DELETE_FROM_FAVORITES";
